# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 18:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('position', models.PositiveIntegerField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Athlete_Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('comment', models.TextField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[('9c', 1500), ('9b+', 1450), ('9b', 1400), ('9a+', 1350), ('9a', 1300), ('8c+', 1250), ('8c', 1200), ('8b+', 1150), ('8b', 1100), ('8a+', 1050), ('8a', 1000), ('7c+', 950), ('7c', 900), ('7b+', 850), ('7b', 800), ('7a+', 750), ('7a', 700), ('6c+', 650), ('6c', 600), ('6b+', 550), ('6b', 500), ('6a+', 450), ('6a', 400), ('5c+', 350), ('5c', 300), ('5b+', 250), ('5b', 200), ('5a+', 150), ('5a', 100)])),
            ],
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.IntegerField(choices=[('flash', 53), ('second go', 2), ('repeat', -51)])),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='athlete_route',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Grades'),
        ),
        migrations.AddField(
            model_name='athlete_route',
            name='remark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Remarks'),
        ),
        migrations.AddField(
            model_name='athlete_route',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Route'),
        ),
    ]
