# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.IntegerField(choices=[(53, 'flash'), (2, 'second go'), (-51, 'repeat')])),
            ],
        ),
        migrations.RenameModel(
            old_name='Grades',
            new_name='Grade',
        ),
        migrations.AlterField(
            model_name='athlete_route',
            name='remark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Remark'),
        ),
        migrations.DeleteModel(
            name='Remarks',
        ),
    ]
