# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20160802_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete_route',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(choices=[(1500, '9c'), (1450, '9b+'), (1400, '9b'), (1350, '9a+'), (1300, '9a'), (1250, '8c+'), (1200, '8c'), (1150, '8b+'), (1100, '8b'), (1050, '8a+'), (1000, '8a'), (950, '7c+'), (900, '7c'), (850, '7b+'), (800, '7b'), (750, '7a+'), (700, '7a'), (650, '6c+'), (600, '6c'), (550, '6b+'), (500, '6b'), (450, '6a+'), (400, '6a'), (350, '5c+'), (300, '5c'), (250, '5b+'), (200, '5b'), (150, '5a+'), (100, '5a')]),
        ),
        migrations.AlterField(
            model_name='route',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
