# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20160802_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='cost',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remark',
            name='cost',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='remark',
            name='remark',
            field=models.CharField(max_length=50),
        ),
    ]
