# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_auto_20160802_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateField(default=django.utils.timezone.now, verbose_name='\u043d\u0430\u0447\u0430\u043b\u043e')),
                ('finished', models.DateField(blank=True, verbose_name='\u043a\u043e\u043d\u0435\u0446')),
            ],
            options={
                'ordering': ['-started'],
                'verbose_name': '\u0441\u0435\u0437\u043e\u043d',
                'verbose_name_plural': '\u0441\u0435\u0437\u043e\u043d\u044b',
            },
        ),
        migrations.AlterModelOptions(
            name='athlete_info',
            options={'verbose_name': '\u0441\u043f\u043e\u0440\u0442\u0441\u043c\u0435\u043d', 'verbose_name_plural': '\u0441\u043f\u043e\u0440\u0442\u0441\u043c\u0435\u043d\u044b'},
        ),
        migrations.AlterModelOptions(
            name='athlete_route',
            options={'ordering': ['-date'], 'verbose_name': '\u0441\u043f\u043e\u0440\u0442\u0441\u043c\u0435\u043d_\u0442\u0440\u0430\u0441\u0441\u0430', 'verbose_name_plural': '\u0441\u043f\u043e\u0440\u0442\u0441\u043c\u0435\u043d\u044b_\u0442\u0440\u0430\u0441\u0441\u044b'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['grade'], 'verbose_name': '\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f', 'verbose_name_plural': '\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'},
        ),
        migrations.AlterModelOptions(
            name='remark',
            options={'ordering': ['remark'], 'verbose_name': '\u043f\u0440\u0438\u043c\u0435\u0447\u0430\u043d\u0438\u0435', 'verbose_name_plural': '\u043f\u0440\u0438\u043c\u0435\u0447\u0430\u043d\u0438\u044f'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-created'], 'verbose_name': '\u0442\u0440\u0430\u0441\u0441\u0430', 'verbose_name_plural': '\u0442\u0440\u0430\u0441\u0441\u044b'},
        ),
        migrations.AddField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='\u0430\u043a\u0442\u0438\u0432\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='athlete_info',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0441\u043f\u043e\u0440\u0442\u0441\u043c\u0435\u043d'),
        ),
        migrations.AlterField(
            model_name='athlete_info',
            name='position',
            field=models.PositiveIntegerField(verbose_name='\u043c\u0435\u0441\u0442\u043e'),
        ),
        migrations.AlterField(
            model_name='athlete_info',
            name='score',
            field=models.FloatField(verbose_name='\u0431\u0430\u043b\u043b\u044b'),
        ),
        migrations.AlterField(
            model_name='athlete_route',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0441\u043f\u043e\u0440\u0442\u0441\u043c\u0435\u043d'),
        ),
        migrations.AlterField(
            model_name='athlete_route',
            name='comment',
            field=models.TextField(blank=True, verbose_name='\u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='athlete_route',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='\u0434\u0430\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='athlete_route',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Grade', verbose_name='\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='athlete_route',
            name='remark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Remark', verbose_name='\u043f\u0440\u0438\u043c\u0435\u0447\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='athlete_route',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Route', verbose_name='\u0442\u0440\u0430\u0441\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='cost',
            field=models.SmallIntegerField(verbose_name='\u0441\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(max_length=10, verbose_name='\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='cost',
            field=models.SmallIntegerField(verbose_name='\u0441\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='remark',
            field=models.CharField(max_length=50, verbose_name='\u043f\u0440\u0438\u043c\u0435\u0447\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='route',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u0441\u0442\u0430\u043d\u043e\u0432\u0449\u0438\u043a'),
        ),
        migrations.AlterField(
            model_name='route',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='\u043f\u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterUniqueTogether(
            name='athlete_route',
            unique_together=set([('athlete', 'route')]),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set([('started', 'finished')]),
        ),
    ]
