# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_auto_20160807_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='current',
            field=models.BooleanField(default=True, verbose_name='\u0442\u0435\u043a\u0443\u0449\u0438\u0439'),
        ),
    ]
