# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_season_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='finished',
            field=models.DateField(blank=True, null=True, verbose_name='\u043a\u043e\u043d\u0435\u0446'),
        ),
    ]
