# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0008_auto_20160808_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete_info',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u0438\u043c\u044f'),
        ),
        migrations.AddField(
            model_name='athlete_info',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u0444\u0430\u043c\u0438\u043b\u0438\u044f'),
        ),
    ]
