# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 20:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0010_auto_20160816_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete_route',
            name='grade',
        ),
        migrations.AddField(
            model_name='route',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rating.Grade', verbose_name='\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u0441\u0442\u0430\u043d\u043e\u0432\u0449\u0438\u043a'),
        ),
    ]
