# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-11 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0012_auto_20160825_2314'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='athlete_route',
            unique_together=set([('athlete', 'route')]),
        ),
    ]
