# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0013_auto_20160911_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0430\u0432\u0442\u043e\u0440'),
        ),
    ]
