# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-02 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0014_auto_20160919_2152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Season',
            new_name='Period',
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['-started'], 'verbose_name': '\u041f\u0435\u0440\u0438\u043e\u0434', 'verbose_name_plural': '\u041f\u0435\u0440\u0438\u043e\u0434'},
        ),
    ]
