# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-22 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0015_auto_20161102_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete_route',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rating.Period', verbose_name='\u043f\u0435\u0440\u0438\u043e\u0434'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='period',
            name='current',
            field=models.BooleanField(default=False, verbose_name='\u0442\u0435\u043a\u0443\u0449\u0438\u0439'),
        ),
        migrations.AlterUniqueTogether(
            name='athlete_route',
            unique_together=set([('athlete', 'route', 'period')]),
        ),
    ]
