# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-08 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0016_auto_20170122_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete_route',
            options={'verbose_name': '\u0441\u043f\u043e\u0440\u0442\u0441\u043c\u0435\u043d_\u0442\u0440\u0430\u0441\u0441\u0430', 'verbose_name_plural': '\u0441\u043f\u043e\u0440\u0442\u0441\u043c\u0435\u043d\u044b_\u0442\u0440\u0430\u0441\u0441\u044b'},
        ),
        migrations.AddField(
            model_name='athlete_info',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture', verbose_name='\u0444\u043e\u0442\u043e'),
        ),
    ]
